### ISSUE TITLE
Error Injecting Text

### ISSUE THREAD

**Issue by yradsmikham** [3mcloud/MDACE#6]
I attempting to follow the instructions to inject text into JSON by running the following command:

`python3 inject-note-text.py --noteevents NOTEEVENTS.csv \
                            --data-dir data/ \
                            --out-dir with_text/gold`
                            
However, I am receiving the following error:

```
➜  MDACE git:(main) ✗ python3 inject-note-text.py --noteevents NOTEEVENTS.csv --data-dir data --out-dir with_text/gold
INFO:inject-note-text.py:Loading NOTEEVENTS.csv
INFO:inject-note-text.py:Injecting text and persisting to /Users/yvonne/microsoft/MDACE/with_text/gold
Traceback (most recent call last):
  File "/Users/yvonne/microsoft/MDACE/inject-note-text.py", line 90, in <module>
    main(parser.parse_args())
  File "/Users/yvonne/microsoft/MDACE/inject-note-text.py", line 67, in main
    inject_and_persist(notes_map, args.data_dir, args.out_dir)
  File "/Users/yvonne/microsoft/MDACE/inject-note-text.py", line 37, in inject_and_persist
    admission = inject_note_text(notes_map, json.load(ifp))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yvonne/microsoft/MDACE/inject-note-text.py", line 15, in inject_note_text
    text = notes_map[note["note_id"]]
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 44580
```

Any idea what is causing this error and how to resolve it?

Python version 3.11.7, running on Macbook Pro M1.

Thank you!

**Comment by yradsmikham** [comment]
Resolved!
